# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[publish]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Vscode release plugin
      uses: JCofman/vscodeaction@v2.0.1
      env:
        PUBLISHER_TOKEN: ${{ secrets.VSCE_TOKEN }}
      with:
        args: publish -p $VSCE_TOKEN
